### ISSUE TITLE
getLocalName() shall return positive numbers only

### ISSUE THREAD

**Issue by qa41yjus** [esa/CCSDS_MO_TRANS#3]
I would suggest to change the following line:

https://github.com/esa/CCSDS_MO_TRANS/blob/master/CCSDS_MAL_TRANSPORT_GEN/src/main/java/esa/mo/mal/transport/gen/GENTransport.java#L841

to this statement (in order to ensure a positive integer as random endpoint name, because otherwise you get problems with the URI schemes where the consumer's source or destination id starts with a minus):

localName = String.valueOf(RANDOM_NAME.nextInt(Integer.MAX_VALUE));

**Comment by SamCooper** [comment]
If it is an issue for a derived transport they should override and change the method.

**Comment by qa41yjus** [comment]
@SamCooper: According to the email exchange with CesarCoelho from 4th January, this issue shall be re-opened and limit the random endpoint generation to positive numbers only on the generic transport.
