### ISSUE TITLE
TCPIPTransport doesn't close socket

### ISSUE THREAD

**Issue by taguan** [esa/CCSDS_MO_TRANS#33]
Hello,

It seems like the TCPIPTransport "close()" method doesn't close the socket it opened in the "init()" method
`ServerSocket serverSocket = new ServerSocket(serverPort, 0, serverHostAddr);` (line 200)

The socket is only a local variable, the class doesn't keep any reference for closing it.

**Comment by CesarCoelho** [comment]
Hi Benoit,

The online version is outdated.
We already have an updated version that follows the latest MAL-TCP/IP book.
We are currently under the screening processing to assure that the code is "legally safe". We will push the latest version as soon as this process is done.
Could you let me know which project are you working on?

Best regards,
César Coelho

**Comment by taguan** [comment]
Hi César,

Glad to read that a new version is coming... Is there a way to be notified when the new version will be published on Maven? Do you have any estimation on when it will be available?

I am working on the MO adaptation layer in EGS-CC.

Kind regards

**Comment by CesarCoelho** [comment]
I don't think that there's a notification system in maven central.
From previous experience, this process takes a few months.
I have a few questions to you, can we talk via email? Your account doesn't seem to have a public email address. Could you please send me an email? Thanks

**Comment by gbonnefille** [comment]
Hi @CesarCoelho ,

We already use a pre-version of the new TCP/IP transport layer. We are also interested in the roadmap of this component. Or, eventually, a new pre-release version.

Furthermore, while testing this component for interoperability with [C implementation](https://github.com/ccsdsmo/malc/), we found some issues. We started to report them via a contractual contact, but we do not have feedback yet. Are you interested in these informations directly?

Best regards

**Comment by CesarCoelho** [comment]
Hi @gbonnefille ,

Yes, I am very interested in receiving this information directly. I am also using the TCP/IP here on my side and I have also found some problems. I suspect that we are finding the same problems twice and  independently.
In relation to a roadmap, the MAL-TCP/IP CCSDS standard has been drafted, and reviewed by all the Agencies. We received the comments and updated the book, we are now in the last phase of approval from the CCSDS.
We did send the implementation for the screening process and we will make it available online when it is ready.

Best regards,
César Coelho

**Comment by CesarCoelho** [comment]
Closed?

**Comment by CesarCoelho** [comment]
Hi @taguan and @gbonnefille ,

Can you check the new TCP/IP implementation?
We have been using it for the past months and we haven't found any major problems.

Could you confirm that we can close this issue?

**Comment by taguan** [comment]
Hi @CesarCoelho ,
I am currently not in a position to test the fix (our project is currently on hold)... I suggest that you close this if you believe that you have fixed it and I will contact you back later if there are additional issues.

@gbonnefille is probably in a better position to provide a real feedback as they are directly using the transport layer...

Thanks a lot

**Comment by gbonnefille** [comment]
Technically speaking, the problem reported in this issue seems to be closed (at least) by commit 582e0e71d387d9789b11ffa1d05a782a8dc90956.

**Comment by taguan** [comment]
Closing as this issue seems fixed as per code inspection
