### ISSUE TITLE
TCPIPSplitBinaryStreamFactory no more exists

### ISSUE THREAD

**Issue by gbonnefille** [esa/CCSDS_MO_TRANS#38]
The [README.md](https://github.com/esa/CCSDS_MO_TRANS/blob/master/CCSDS_MAL_TRANSPORT_TCPIP/README.md) still refers to a no more existing TCPIPSplitBinaryStreamFactory class.

**Comment by CesarCoelho** [comment]
Done:
https://github.com/esa/CCSDS_MO_TRANS/pull/39

**Comment by gbonnefille** [comment]
Merged.
