### ISSUE TITLE
Create tag/release 1.7

### ISSUE THREAD

**Issue by gbonnefille** [esa/CCSDS_MO_TRANS#45]
It seems that a new version was released in december 17: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22int.esa.ccsds.mo%22

Is it possible to tag the corresponding version in Git?
Eventually, modifying the version of the REACTOR_TRANSPORTS' POM can also help appreciating the state of the project.

**Comment by dmarszk** [comment]
Created tag 1.7 in the corresponding repositories.
