### ISSUE TITLE
Add unit tests to split bynary encoding layer

### ISSUE THREAD

**Issue by gbonnefille** [esa/CCSDS_MO_TRANS#7]
In order to integrate this implementation with the [malc](https://github.com/ccsdsmo/malc/) implementation, we had to adapt the split binary encoding. Doing this, we started a set of tests to experiment and validate the behaviour of the current implementation. These tests reflect our understanding of the [Mission Operations - Message Abstraction Layer Binding to TCP/IP Transport and Split Binary Encoding Draft Recommended Standard ](http://public.ccsds.org/sites/cwe/rids/Lists/CCSDS%205242R1/Attachments/524x2r1.pdf).

We share this work on https://github.com/gbonnefille/CCSDS_MO_TRANS/tree/split-binary-unit-tests

We would be really proud if this work can be integrated in the main repository. Before that, @SamCooper can you give us your feedback about these tests?

**Comment by SamCooper** [comment]
Hi, it looks really good! Nice work.

I'd be happy to pull this across, can you do a merge on your tree with the latest ESA master and then make a pull request via GitHub please and I'll pull it over.

**Comment by gbonnefille** [comment]
Please, note that these tests fail, revealing deviations to the standard (or misundertanding of this standard by us). So we want to be sure the main goal of the CSDS_MAL_ENCODING_BINARY_SPLIT module is to implement the referenced standard.

**Comment by SamCooper** [comment]
Oh, right, OK, good to know. 

The standard came after the implementation so at the moment it does not fully comply to the specification as you have detected. This is currently being fixed as part of the approval process for the specification and once done the code will be updated to match the specification.

If you could make the pull request then I will leave that hanging until the specification is published and the implementation fixed. Once done then I will pull across your unit tests as, in theory, they should pass at this point.

**Comment by gbonnefille** [comment]
Please, check PullRequest #11.
